#ifndef _GAME_H_INCLUDED_
#define _GAME_H_INCLUDED_

#include <SDL.h>
#include "scene.h"

#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 600

#define SPACESHIP_MAX_SPEED 300
#define SPACESHIP_ACCELERATION 0.9
#define SPACESHIP_DECELERATION 0.3
#define SPACESHIP_ANGULAR_VELOCITY PI

#define BULLET_SPEED 400

#define ASTEROID_LARGE 40
#define ASTEROID_MEDIUM 20
#define ASTEROID_SMALL 10
#define ASTEROID_FRAGMENTS 2
#define ASTEROID_SPEED 60
#define ASTEROID_MIN_SIDES 10
#define ASTEROID_MAX_SIDES 15

#define LEVEL_INITIAL_ASTEROIDS 4
#define LEVEL_ASTEROID_INCREMENT 2

#define GAME_INITIAL_LIVES 3
#define GAME_RESPAWNING_TIME 3
#define GAME_INVINCIBILITY_TIME 3

typedef enum {
    SPACESHIP_STATE_OK,
    SPACESHIP_STATE_DESTROYED,
    SPACESHIP_STATE_INVINCIBLE
} Spaceship_State;

extern SDL_Renderer *renderer;
extern float time_step;
extern Scene game;

#endif
